'use client';

import { useState, useCallback, useMemo, useRef } from 'react';
import { ChatContainer } from '@/components/chat';
import { ConversationSidebar, MobileDrawerTrigger } from '@/components/sidebar';
import { useConversations, generateTitleFromMessage, useWelcomeFlow, formatPreferencesContext, useChat } from '@/hooks';
import type { Message } from '@/types';

export default function Home() {
  const {
    conversations,
    isLoadingList,
    currentConversationId,
    currentMessages,
    isLoadingConversation,
    selectConversation,
    createConversation,
    deleteConversation,
    addMessage,
    updateTitle,
    clearCurrentConversation,
  } = useConversations();

  const {
    isNewUser,
    completePreferences,
  } = useWelcomeFlow();

  const { sendMessage: sendChatMessage } = useChat();

  // Track messages added during this session, keyed by conversation ID
  const [sessionMessagesMap, setSessionMessagesMap] = useState<Record<string, Message[]>>({});
  const [isTyping, setIsTyping] = useState(false);
  const [hasAutoGeneratedTitle, setHasAutoGeneratedTitle] = useState(false);
  
  // Ref to track the current streaming assistant message
  const streamingMessageRef = useRef<{ id: string; content: string } | null>(null);
  
  // Get session messages for current conversation
  const sessionMessages = useMemo(() => 
    currentConversationId ? sessionMessagesMap[currentConversationId] ?? [] : [],
    [currentConversationId, sessionMessagesMap]
  );
  
  // Derive local messages from current conversation + session messages
  const localMessages = useMemo(() => {
    // Prioritize currentMessages from server, fall back to session messages
    if (currentMessages.length > 0) {
      return currentMessages;
    }
    return sessionMessages;
  }, [currentMessages, sessionMessages]);

  const handleSendMessage = useCallback(async (content: string) => {
    // If no conversation selected, create one
    let conversationId = currentConversationId;
    if (!conversationId) {
      try {
        conversationId = await createConversation();
      } catch (error) {
        console.error('Failed to create conversation:', error);
        return;
      }
    }

    // Add user message
    const userMessage: Message = {
      id: crypto.randomUUID(),
      role: 'user',
      content,
      createdAt: new Date(),
    };
    
    // Update session messages for this conversation
    setSessionMessagesMap((prev) => ({
      ...prev,
      [conversationId!]: [...(prev[conversationId!] ?? []), userMessage],
    }));
    addMessage(userMessage);
    setIsTyping(true);

    // Auto-generate title from first message
    if (!hasAutoGeneratedTitle && localMessages.length === 0) {
      const title = generateTitleFromMessage(content);
      updateTitle(conversationId, title);
      setHasAutoGeneratedTitle(true);
    }

    // Create a placeholder for the assistant message
    const assistantMessageId = crypto.randomUUID();
    streamingMessageRef.current = { id: assistantMessageId, content: '' };
    const capturedConversationId = conversationId;

    // Call the real chat API with streaming
    await sendChatMessage(content, {
      conversationId,
      onText: (text: string) => {
        // Accumulate the streamed text
        if (streamingMessageRef.current) {
          streamingMessageRef.current.content += text;
          
          // Update the assistant message in state
          const updatedContent = streamingMessageRef.current.content;
          setSessionMessagesMap((prev) => {
            const currentMessages = prev[capturedConversationId] ?? [];
            const existingIndex = currentMessages.findIndex(m => m.id === assistantMessageId);
            
            if (existingIndex >= 0) {
              // Update existing message
              const updated = [...currentMessages];
              updated[existingIndex] = {
                ...updated[existingIndex],
                content: updatedContent,
              };
              return { ...prev, [capturedConversationId]: updated };
            } else {
              // Add new message
              return {
                ...prev,
                [capturedConversationId]: [
                  ...currentMessages,
                  {
                    id: assistantMessageId,
                    role: 'assistant' as const,
                    content: updatedContent,
                    createdAt: new Date(),
                  },
                ],
              };
            }
          });
        }
      },
      onDone: () => {
        setIsTyping(false);
        streamingMessageRef.current = null;
      },
      onError: (error: string) => {
        console.error('Chat error:', error);
        setIsTyping(false);
        
        // Add error message
        const errorMessage: Message = {
          id: crypto.randomUUID(),
          role: 'assistant',
          content: `I apologize, but I encountered an error: ${error}. Please try again.`,
          createdAt: new Date(),
        };
        
        setSessionMessagesMap((prev) => ({
          ...prev,
          [capturedConversationId]: [...(prev[capturedConversationId] ?? []), errorMessage],
        }));
        streamingMessageRef.current = null;
      },
    });
  }, [
    currentConversationId,
    createConversation,
    addMessage,
    updateTitle,
    hasAutoGeneratedTitle,
    localMessages.length,
    sendChatMessage,
  ]);

  const handleNewConversation = useCallback(() => {
    clearCurrentConversation();
    setHasAutoGeneratedTitle(false);
  }, [clearCurrentConversation]);

  const handleSelectConversation = useCallback(async (id: string) => {
    await selectConversation(id);
    setHasAutoGeneratedTitle(true); // Existing conversation already has a title
  }, [selectConversation]);

  const handleDeleteConversation = useCallback(async (id: string) => {
    // Clear session messages for this conversation
    setSessionMessagesMap((prev) => {
      const updated = { ...prev };
      delete updated[id];
      return updated;
    });
    await deleteConversation(id);
  }, [deleteConversation]);

  const handlePreferencesComplete = useCallback((prefs: {
    budget?: 'budget' | 'moderate' | 'luxury';
    travelStyle?: 'solo' | 'couple' | 'family' | 'friends';
    interests?: ('relaxation' | 'adventure' | 'culture' | 'nightlife')[];
  }) => {
    // Save preferences
    completePreferences(prefs);
    
    // Format the context for AI (used when sending messages)
    formatPreferencesContext(prefs);
  }, [completePreferences]);

  return (
    <main className="dark flex h-screen">
      {/* Desktop Sidebar */}
      <ConversationSidebar
        conversations={conversations}
        currentConversationId={currentConversationId}
        onSelectConversation={handleSelectConversation}
        onNewConversation={handleNewConversation}
        onDeleteConversation={handleDeleteConversation}
        isLoading={isLoadingList}
      />

      {/* Main Chat Area */}
      <div className="flex-1 flex flex-col min-w-0">
        <ChatContainer
          messages={localMessages}
          onSendMessage={handleSendMessage}
          isTyping={isTyping}
          isLoading={isLoadingConversation}
          isNewUser={isNewUser}
          onPreferencesComplete={handlePreferencesComplete}
          mobileMenuTrigger={
            <MobileDrawerTrigger
              conversations={conversations}
              currentConversationId={currentConversationId}
              onSelectConversation={handleSelectConversation}
              onNewConversation={handleNewConversation}
              onDeleteConversation={handleDeleteConversation}
              isLoading={isLoadingList}
            />
          }
        />
      </div>
    </main>
  );
}
