'use client';

import { useState, useCallback, useEffect } from 'react';
import { ChatContainer } from '@/components/chat';
import { ConversationSidebar, MobileDrawerTrigger } from '@/components/sidebar';
import { useConversations, generateTitleFromMessage, useWelcomeFlow, formatPreferencesContext } from '@/hooks';
import type { Message } from '@/types';

// Demo responses for the travel agent
const demoResponses = [
  "I'd love to help you plan your trip! Could you tell me more about what kind of experience you're looking for? Are you interested in beaches, mountains, cities, or cultural experiences?",
  "That sounds wonderful! Based on your interests, I'd recommend considering these destinations:\n\n🏝️ **Bali, Indonesia** - Perfect blend of beaches, temples, and culture\n🗼 **Tokyo, Japan** - Amazing food, fascinating history, and modern wonders\n🏔️ **Swiss Alps** - Breathtaking mountain scenery and outdoor adventures\n\nWould you like me to dive deeper into any of these options?",
  "Great choice! Let me put together a sample itinerary for you. What dates are you thinking, and how many travelers will be joining?",
  "I've noted that down! Here's a preliminary 7-day itinerary I'd suggest:\n\n**Day 1-2:** Arrive and explore the local area\n**Day 3-4:** Cultural excursions and guided tours\n**Day 5-6:** Adventure activities and hidden gems\n**Day 7:** Relaxation and departure\n\nWould you like me to add specific activities or adjust anything?",
];

// Personalized first response based on user preferences
function getPersonalizedGreeting(preferences: {
  budget?: 'budget' | 'moderate' | 'luxury';
  travelStyle?: 'solo' | 'couple' | 'family' | 'friends';
  interests?: ('relaxation' | 'adventure' | 'culture' | 'nightlife')[];
}): string {
  const parts: string[] = [];
  
  if (preferences.budget) {
    const budgetText = {
      budget: "I'll focus on great value destinations",
      moderate: "I'll find you the best balance of quality and value",
      luxury: "I'll suggest premium experiences and accommodations",
    };
    parts.push(budgetText[preferences.budget]);
  }
  
  if (preferences.travelStyle) {
    const styleText = {
      solo: "perfect for solo exploration",
      couple: "ideal for romantic getaways",
      family: "with family-friendly activities",
      friends: "great for group adventures",
    };
    parts.push(styleText[preferences.travelStyle]);
  }
  
  if (preferences.interests && preferences.interests.length > 0) {
    const interestLabels = {
      relaxation: 'relaxation',
      adventure: 'adventure',
      culture: 'cultural experiences',
      nightlife: 'nightlife',
    };
    const interests = preferences.interests.map(i => interestLabels[i]).join(', ');
    parts.push(`focusing on ${interests}`);
  }

  if (parts.length === 0) {
    return "I'd love to help you plan your trip! Could you tell me more about what kind of experience you're looking for?";
  }
  
  return `Thanks for sharing your preferences! ${parts.join(', ')}. Now, tell me about your dream destination or what kind of trip you're looking for!`;
}

export default function Home() {
  const {
    conversations,
    isLoadingList,
    currentConversationId,
    currentMessages,
    isLoadingConversation,
    selectConversation,
    createConversation,
    deleteConversation,
    addMessage,
    updateTitle,
    clearCurrentConversation,
  } = useConversations();

  const {
    isNewUser,
    preferences,
    completePreferences,
  } = useWelcomeFlow();

  const [localMessages, setLocalMessages] = useState<Message[]>([]);
  const [isTyping, setIsTyping] = useState(false);
  const [responseIndex, setResponseIndex] = useState(0);
  const [hasAutoGeneratedTitle, setHasAutoGeneratedTitle] = useState(false);

  // Sync local messages with current conversation messages
  useEffect(() => {
    setLocalMessages(currentMessages);
    setHasAutoGeneratedTitle(false);
  }, [currentMessages]);

  const handleSendMessage = useCallback(async (content: string) => {
    // If no conversation selected, create one
    let conversationId = currentConversationId;
    if (!conversationId) {
      try {
        conversationId = await createConversation();
      } catch (error) {
        console.error('Failed to create conversation:', error);
        return;
      }
    }

    // Add user message
    const userMessage: Message = {
      id: crypto.randomUUID(),
      role: 'user',
      content,
      createdAt: new Date(),
    };
    
    setLocalMessages((prev) => [...prev, userMessage]);
    addMessage(userMessage);
    setIsTyping(true);

    // Auto-generate title from first message
    if (!hasAutoGeneratedTitle && localMessages.length === 0) {
      const title = generateTitleFromMessage(content);
      updateTitle(conversationId, title);
      setHasAutoGeneratedTitle(true);
    }

    // Simulate AI response after a delay
    setTimeout(() => {
      const assistantMessage: Message = {
        id: crypto.randomUUID(),
        role: 'assistant',
        content: demoResponses[responseIndex % demoResponses.length],
        createdAt: new Date(),
      };
      
      setLocalMessages((prev) => [...prev, assistantMessage]);
      addMessage(assistantMessage);
      setResponseIndex((prev) => prev + 1);
      setIsTyping(false);
    }, 1500 + Math.random() * 1000);
  }, [
    currentConversationId,
    createConversation,
    addMessage,
    updateTitle,
    hasAutoGeneratedTitle,
    localMessages.length,
    responseIndex,
  ]);

  const handleNewConversation = useCallback(() => {
    clearCurrentConversation();
    setLocalMessages([]);
    setResponseIndex(0);
    setHasAutoGeneratedTitle(false);
  }, [clearCurrentConversation]);

  const handleSelectConversation = useCallback(async (id: string) => {
    await selectConversation(id);
    setHasAutoGeneratedTitle(true); // Existing conversation already has a title
  }, [selectConversation]);

  const handleDeleteConversation = useCallback(async (id: string) => {
    await deleteConversation(id);
  }, [deleteConversation]);

  const handlePreferencesComplete = useCallback((prefs: {
    budget?: 'budget' | 'moderate' | 'luxury';
    travelStyle?: 'solo' | 'couple' | 'family' | 'friends';
    interests?: ('relaxation' | 'adventure' | 'culture' | 'nightlife')[];
  }) => {
    // Save preferences
    completePreferences(prefs);
    
    // Log the context that would be used for AI
    const context = formatPreferencesContext(prefs);
    if (context) {
      console.log('User preferences context:', context);
    }
  }, [completePreferences]);

  return (
    <main className="dark flex h-screen">
      {/* Desktop Sidebar */}
      <ConversationSidebar
        conversations={conversations}
        currentConversationId={currentConversationId}
        onSelectConversation={handleSelectConversation}
        onNewConversation={handleNewConversation}
        onDeleteConversation={handleDeleteConversation}
        isLoading={isLoadingList}
      />

      {/* Main Chat Area */}
      <div className="flex-1 flex flex-col min-w-0">
        <ChatContainer
          messages={localMessages}
          onSendMessage={handleSendMessage}
          isTyping={isTyping}
          isLoading={isLoadingConversation}
          isNewUser={isNewUser}
          onPreferencesComplete={handlePreferencesComplete}
          mobileMenuTrigger={
            <MobileDrawerTrigger
              conversations={conversations}
              currentConversationId={currentConversationId}
              onSelectConversation={handleSelectConversation}
              onNewConversation={handleNewConversation}
              onDeleteConversation={handleDeleteConversation}
              isLoading={isLoadingList}
            />
          }
        />
      </div>
    </main>
  );
}
